version: "3.8"

networks:
  otlp_network:
    name: otlp_network
    external: true

volumes:
  loki:

x-loki:
  &loki
  image: &loki-img grafana/loki:2.8.3
  labels:
    - com.host.plane=cp
  networks:
    - otlp_network
  restart: always 
  environment:
    # expand-env example
    - LOG_FORMAT=json
  ports:
    - "3100"
    - "7946"
  volumes:
    - ./config/loki.yaml:/etc/loki/loki.yaml
    - ./config/overrides.yaml:/etc/overrides.yaml
    - ./rules:/loki/rules:ro

services:

  init:
    image: *loki-img
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/loki"
    volumes:
      - ./loki:/loki
    networks:
      - otlp_network

  loki-read:
    <<: *loki
    command: "-config.file=/etc/loki/loki.yaml -runtime-config.file=/etc/overrides.yaml -target=read -config.expand-env=true"
    deploy:
      mode: replicated
      replicas: 3


  loki-write:
    <<: *loki
    command: "-config.file=/etc/loki/loki.yaml -target=write -config.expand-env=true"
    deploy:
      mode: replicated
      replicas: 3


