---
version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: otel-test-jaeger
    ports:
      - "127.0.0.1:6831:6831/udp"
      - "127.0.0.1:16686:16686"
      - "127.0.0.1:16687:16687"
      - "127.0.0.1:16685:16685"
      - "127.0.0.1:14269:14269"
    environment:
      -  METRICS_STORAGE_TYPE=prometheus
      -  PROMETHEUS_SERVER_URL=http://otel-test-prometheus:9090
      -  PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
      -  MONITOR_MENU_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    container_name: otel-test-prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "127.0.0.1:9090:9090"