version: "3.8"

networks:
  otlp_network:
    name: otlp_network
    external: true

volumes:
  alertmanager-data:
  loki:

x-loki:
  &loki
  image: &loki-img grafana/loki:2.8.3
  labels:
    - com.host.plane=cp
  networks:
    - otlp_network
  restart: always 
  ports:
    - "3100"
    - "7946"
  volumes:
    - ./config/loki.yaml:/etc/loki/loki.yaml
    - ./config/overrides.yaml:/etc/overrides.yaml
    - ./rules:/loki/rules:ro

services:

  init:
    image: *loki-img
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/loki"
    volumes:
      - ./loki:/loki
    networks:
      - otlp_network

  loki-read:
    <<: *loki
    command: "-config.file=/etc/loki/loki.yaml -runtime-config.file=/etc/overrides.yaml -target=read"
    deploy:
      mode: replicated
      replicas: 3


  loki-write:
    <<: *loki
    command: "-config.file=/etc/loki/loki.yaml -target=write"
    deploy:
      mode: replicated
      replicas: 3

  # alertmanager to enable receiving alerts
  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: always
    hostname: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - "./config/alertmanager.yaml:/config/alertmanager.yaml"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yaml --log.level=debug
    networks:
      - otlp_network

  otel-test-promtail:
    image: grafana/promtail:latest
    container_name: otel-test-promtail
    hostname: otel-test-promtail
    volumes:
      - ./config/promtail.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - otlp_network
    labels:
      - com.host.plane=cp
