---
version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: otel-test-jaeger
    ports:
      - "127.0.0.1:6831:6831/udp"
      - "127.0.0.1:16686:16686"
      - "127.0.0.1:16687:16687"
      - "127.0.0.1:16685:16685"
      - "127.0.0.1:14269:14269"
    environment:
      -  METRICS_STORAGE_TYPE=prometheus
      -  PROMETHEUS_SERVER_URL=http://otel-test-prometheus:9090
      -  PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
      -  MONITOR_MENU_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    container_name: otel-test-prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "127.0.0.1:9090:9090"

  grafana:
    image: grafana/grafana:9.4.3
    container_name: otel-test-grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "127.0.0.1:3000:3000"

  tempo:
    image: grafana/tempo:latest
    container_name: otel-test-tempo
    command: ["-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "127.0.0.1:14268:14268"  # jaeger ingest
      - "127.0.0.1:3200:3200"   # tempo
      - "127.0.0.1:9095:9095" # tempo grpc
      - "127.0.0.1:4317:4317"  # otlp grpc
      - "127.0.0.1:4318:4318"  # otlp http
      - "127.0.0.1:9411:9411"   # zipkin