version: "3.7"

networks:
  otlp_network:
    name: otlp_network
    external: true


x-vmagent:
  &vmagent
  image: victoriametrics/vmagent:v1.93.0
  networks:
    - otlp_network
  labels:
      - com.host.plane=cp
  deploy:
    replicas: 1
    restart_policy:
      condition: on-failure
  volumes:
    - ./config:/config
  expose:
    - 8429


x-otel-collector:
  &otel-collector
  image: otel/opentelemetry-collector:0.61.0
  command: ["--config=/etc/otel-collector.yaml"]
  volumes:
    - ./config/otelcollector.yaml:/etc/otel-collector.yaml
  networks:
    - otlp_network
  labels:
      - com.host.plane=cp


services:
  vmagent-cp:
    <<: *vmagent
    container_name: vmagent-cp
    hostname: vmagent-cp
    command:
      - "--promscrape.config=/config/prometheus-cp.yaml"
      - "--remoteWrite.url=http://load-balancer:9009/api/v1/push"
      - "--remoteWrite.headers=X-Scope-OrgID:otlp-test-cp" # Providing tenant name to headers

  vmagent-dp:
    <<: *vmagent
    container_name: vmagent-dp
    hostname: vmagent-dp
    command:
      - "--promscrape.config=/config/prometheus-dp.yaml"
      - "--remoteWrite.url=http://load-balancer:9009/api/v1/push"
      - "--remoteWrite.headers=X-Scope-OrgID:otlp-test-dp" # Providing tenant name to headers
  

  promtail-cp:
    image: grafana/promtail:latest        
    container_name: promtail-cp
    hostname: promtail-cp
    volumes:
      - ./config/promtail-cp.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./config/test.log:/test.log
    networks:
      - otlp_network
    labels:
      - com.host.plane=cp

  promtail-dp:
    image: grafana/promtail:latest        
    container_name: promtail-dp
    hostname: promtail-dp
    volumes:
      - ./config/promtail-dp.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - otlp_network
    labels:
      - com.host.plane=cp


  otel-collector-dp:
    <<: *otel-collector
    container_name: otel-collector-dp
    hostname: otel-collector-dp