# export DOCKER_BUILDKIT=1 
# export COMPOSE_DOCKER_CLI_BUILD=1

x-service-template:
  &service
  env_file:
    - .env
  networks:
    - otlp_network


services:

# Workers




  a:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=A

  b:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=B
  c:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=C

  d:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=D

  e:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=E

  f:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=F
# Networking

networks:
  otlp_network:
    name: otlp_network
    external: true