# export DOCKER_BUILDKIT=1 
# export COMPOSE_DOCKER_CLI_BUILD=1

x-service-template:
  &service
  env_file:
    - .env
  networks:
    - otlp_network
  labels:
      - com.host.plane=dp


services:

# Workers

  a:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=A
    hostname: otel-test-service-a

  b:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=B
    hostname: otel-test-service-b
  c:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=C
    hostname: otel-test-service-c

  d:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=D
    hostname: otel-test-service-d

  e:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=E
    hostname: otel-test-service-e

  f:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=F
    hostname: otel-test-service-f
# Networking

networks:
  otlp_network:
    name: otlp_network
    external: true