version: "3.7"

networks:
  otlp_network:
    name: otlp_network
    external: true


volumes:
  mimir-1-data:
  mimir-2-data:
  mimir-3-data:

x-mimir-v-config: &mimir-v-config
  "./config/mimir.yaml:/etc/mimir.yaml"


x-mimir-v-runtime: &mimir-v-runtime
  "./config/runtime.yaml:/etc/runtime.yaml"

x-mimir-v-am: &mimir-v-am
  "./config/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml"

x-mimir-v-prst-tsdb-1: &mimir-v-prst-tsdb-1
  "./data/.1:/data:delegated"

x-mimir-v-prst-tsdb-2: &mimir-v-prst-tsdb-2
  "./data/.2:/data:delegated"

x-mimir-v-prst-tsdb-3: &mimir-v-prst-tsdb-3
  "./data/.3:/data:delegated"

x-mimir:
  &mimir
  image: grafana/mimir:latest
  networks:
    - otlp_network
  labels:
      - com.host.plane=cp
  volumes:
    - *mimir-v-config
    - *mimir-v-runtime
    - *mimir-v-am

services:

  memcached:
    image: "memcached:1.6.19-alpine"
    hostname: memcached
    networks:
      - otlp_network
    labels:
      - com.host.plane=cp


  mimir-backend-1:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=backend", "-tenant-federation.enabled=true"]
    hostname: "mimir-backend-1"

  mimir-backend-2:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=backend", "-tenant-federation.enabled=true"]
    hostname: "mimir-backend-2"

  mimir-backend-3:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=backend", "-tenant-federation.enabled=true"]
    hostname: "mimir-backend-3"


  mimir-write-1:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=write", "-tenant-federation.enabled=true"]
    hostname: "mimir-write-1"
    volumes_from:
      - mimir-backend-1
    volumes:
      - *mimir-v-prst-tsdb-1

  mimir-write-2:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=write", "-tenant-federation.enabled=true"]
    hostname: "mimir-write-2"
    volumes_from:
      - mimir-backend-2
    volumes:
      - *mimir-v-prst-tsdb-2

  mimir-write-3:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=write", "-tenant-federation.enabled=true"]
    hostname: "mimir-write-3"
    volumes_from:
      - mimir-backend-3
    volumes:
      - *mimir-v-prst-tsdb-3

  mimir-read-1:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=read", "-tenant-federation.enabled=true"]
    hostname: "mimir-read-1"

  mimir-read-2:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=read", "-tenant-federation.enabled=true"]
    hostname: "mimir-read-2"

  mimir-read-3:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=read", "-tenant-federation.enabled=true"]
    hostname: "mimir-read-3"



