# syntax = edrevo/dockerfile-plus

FROM python:3.10-slim

LABEL org.opencontainers.image.source="https://github.com/northpowered/temporal-otlp"

LABEL version="0.1.0"

ENV POETRY_VIRTUALENVS_CREATE=false

WORKDIR /app

COPY poetry.lock poetry.lock 

COPY pyproject.toml pyproject.toml

RUN pip install poetry

RUN poetry install --no-root