version: "3.7"

networks:
  otlp_network:
    name: otlp_network
    external: true


volumes:
  mimir-1-data:
  mimir-2-data:
  mimir-3-data:


x-mimir:
  &mimir
  image: grafana/mimir:latest
  networks:
    - otlp_network
  labels:
      - com.host.plane=cp
  volumes:
    - ./config/mimir.yaml:/etc/mimir.yaml
    - ./config/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml

services:

  # mimir-ingester:
  #   <<: *mimir
  #   command: ["-config.file=/etc/mimir.yaml","-target=ingester"]
  #   hostname: mimir-ingester
  #   deploy:
  #     mode: replicated
  #     replicas: 2
  memcached:
    image: "memcached:1.6.19-alpine"
    hostname: memcached
    networks:
      - otlp_network
    labels:
      - com.host.plane=cp


  mimir-backend-1:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=backend", "-tenant-federation.enabled=true"]
    hostname: "mimir-backend-1"

  mimir-backend-2:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=backend", "-tenant-federation.enabled=true"]
    hostname: "mimir-backend-2"

  mimir-backend-3:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=backend", "-tenant-federation.enabled=true"]
    hostname: "mimir-backend-3"


  mimir-write-1:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=write", "-tenant-federation.enabled=true"]
    hostname: "mimir-write-1"

  mimir-write-2:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=write", "-tenant-federation.enabled=true"]
    hostname: "mimir-write-2"

  mimir-write-3:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=write", "-tenant-federation.enabled=true"]
    hostname: "mimir-write-3"

  mimir-read-1:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=read", "-tenant-federation.enabled=true"]
    hostname: "mimir-read-1"

  mimir-read-2:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=read", "-tenant-federation.enabled=true"]
    hostname: "mimir-read-2"

  mimir-read-3:
    <<: *mimir
    command: ["-config.file=/etc/mimir.yaml","-target=read", "-tenant-federation.enabled=true"]
    hostname: "mimir-read-3"



  otel-test-prometheus:
    image: prom/prometheus:latest
    container_name: otel-test-prometheus
    hostname: otel-test-prometheus
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-remote-write-receiver'
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - otlp_network
    labels:
      - com.host.plane=cp