version: "3.7"

networks:
  otlp_network:
    name: otlp_network
    external: true


volumes:
  mimir-1-data:
  mimir-2-data:
  mimir-3-data:
  minio-data:

services:

  minio:
  # Minio is S3-compatible persistent storage for blocks, rules, and alerts
    image: minio/minio
    hostname: minio
    entrypoint: ["sh","/minio-init.sh"]
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    environment:
      - MINIO_ROOT_USER=mimir
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - minio-data:/data:rw
      - ./config/minio-init.sh:/minio-init.sh
    ports:
      - "127.0.0.1:9001:9001"
      - "127.0.0.1:9000:9000"
    networks:
      - otlp_network
    labels:
      - com.host.plane=cp

  load-balancer:
      image: nginx:latest
      volumes:
        - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - "mimir-1"
        - "mimir-2"
        - "mimir-3"
      ports:
        - 9009:9009
      networks:
        - otlp_network
      labels:
        - com.host.plane=cp

  mimir-1:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-1
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-1-data:/data
    networks:
      - otlp_network
    labels:
      - com.host.plane=cp

  mimir-2:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-2
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-2-data:/data
    networks:
      - otlp_network
    labels:
      - com.host.plane=cp

  mimir-3:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-3
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-3-data:/data
    networks:
      - otlp_network
    labels:
      - com.host.plane=cp


  otel-test-prometheus:
    image: prom/prometheus:latest
    container_name: otel-test-prometheus
    hostname: otel-test-prometheus
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-remote-write-receiver'
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - otlp_network
    labels:
      - com.host.plane=cp
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"