version: "3.7"

networks:
  backend_network:
    name: apm_test_network
    external: true


x-vmagent:
  &vmagent
  image: victoriametrics/vmagent:v1.93.0
  networks:
    - backend_network
  labels:
    - com.host.plane=cp
  deploy:
    replicas: 1
    restart_policy:
      condition: on-failure
  volumes:
    - ./config:/config
  expose:
    - 8429


x-otel-collector:
  &otel-collector
  image: otel/opentelemetry-collector:0.61.0
  command: ["--config=/etc/otel-collector.yaml"]
  networks:
    - backend_network
  labels:
    - com.host.plane=cp


services:

  vmagent-dp-dev:
    <<: *vmagent
    container_name: vmagent-dp-dev
    hostname: vmagent-dp-dev
    command:
      - "--promscrape.config=/config/prometheus-dp-dev.yaml"
      - "--remoteWrite.url=http://load-balancer:9009/api/v1/push"
      - "--remoteWrite.headers=X-Scope-OrgID:otlp-test-dp-dev" # Providing tenant name to headers
  
  vmagent-dp-prod:
    <<: *vmagent
    container_name: vmagent-dp-prod
    hostname: vmagent-dp-prod
    command:
      - "--promscrape.config=/config/prometheus-dp-prod.yaml"
      - "--remoteWrite.url=http://load-balancer:9009/api/v1/push"
      - "--remoteWrite.headers=X-Scope-OrgID:otlp-test-dp-prod" # Providing tenant name to headers

  promtail-dp-dev:
    image: grafana/promtail:latest        
    container_name: promtail-dp-dev
    hostname: promtail-dp-dev
    volumes:
      - ./config/promtail-dp-dev.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - backend_network
    labels:
      - com.host.plane=cp

  promtail-dp-prod:
    image: grafana/promtail:latest        
    container_name: promtail-dp-prod
    hostname: promtail-dp-prod
    volumes:
      - ./config/promtail-dp-prod.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - backend_network
    labels:
      - com.host.plane=cp

  otel-collector-dp-dev:
    <<: *otel-collector
    container_name: otel-collector-dp-dev
    hostname: otel-collector-dp-dev
    volumes:
      - ./config/otelcollector-dev.yaml:/etc/otel-collector.yaml

  otel-collector-dp-prod:
    <<: *otel-collector
    container_name: otel-collector-dp-prod
    hostname: otel-collector-dp-prod
    volumes:
      - ./config/otelcollector-prod.yaml:/etc/otel-collector.yaml