# export DOCKER_BUILDKIT=1 
# export COMPOSE_DOCKER_CLI_BUILD=1

networks:
  backend_network:
    name: apm_test_network
    external: true

x-service-template:
  &service
  env_file:
    - .env_dev
  networks:
    - backend_network
  labels:
      - com.host.plane=dp
      - x.mode=dev
  #pid: "host"


services:

# Workers

  a:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=A
    hostname: otel-test-service-a-dev

  b:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=B
    hostname: otel-test-service-b-dev
  c:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=C
    hostname: otel-test-service-c-dev

  d:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=D
    hostname: otel-test-service-d-dev

  e:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=E
    hostname: otel-test-service-e-dev

  f:
    <<: *service
    build:
      context: .
      args:
        - SRV_LETTER=F
    hostname: otel-test-service-f-dev