server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"


clients:
  - url: http://load-balancer:3100/loki/api/v1/push
    tenant_id: otlp-test-cp


scrape_configs:

  - job_name: apm-services
    # use docker.sock to filter containers
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.host.plane=cp"]
    # use container name to create a loki label
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'