server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "debug"

clients:
  - url: http://load-balancer:3100/loki/api/v1/push
    tenant_id: otlp-test-cp

scrape_configs:

  - job_name: apm-services-lb
    # use docker.sock to filter containers
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.host.apm-svc.type=nginx"]
    # use container name to create a loki label
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'svc'
    # nginx json log parcer
    pipeline_stages:
      - json:
          expressions:
            host: host
            request_length: request_length
            output: uri
            method: method
            status: status
            level: status
            upstream_addr: upstream_addr
            user_agent: user_agent
            tenant: tenant

      - template:
          source: output
          template: '{{ .method }} {{ .status }} {{ .Value  }}'
      # How to create LEVEL label if you`re a lobster
      - template:
          source: level
          template: "\
            {{ if and (ge (int .status) 400) (lt (int .status) 500) }}\
              WARN\
            {{ else }}\
              {{ if (ge (int .status) 500) }}\
                ERROR\
              {{ else }}\
                INFO\
              {{ end }}\
            {{ end }}\
            "
      - labels:
          user_agent:
          tenant:
          status:
          level:
      - output:
          source: output

  - job_name: apm-services-all
    # use docker.sock to filter containers
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 15s
        # TODO: exclude nginx job from this filter
        filters:
          - name: label
            values: ["com.host.plane=cp"]
    # use container name to create a loki label
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

