version: "3.7"

networks:
  backend_network:
    name: ${NETWORK_NAME}
    external: true


services:

  grafana:
    image: grafana/grafana:${VERSION_GRAFANA}
    container_name: grafana
    hostname: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana:rw
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-oncall-app
      - GF_INSTALL_PLUGINS=grafana-oncall-app
    ports:
      - "127.0.0.1:${GRAFANA_PORT}:3000"
    networks:
      - backend_network
    labels:
      - com.host.plane=cp


  