version: "3.8"

networks:
  backend_network:
    name: ${NETWORK_NAME}
    external: true

volumes:
  loki:

x-loki:
  &loki
  image: &loki-img grafana/loki:2.8.3
  labels:
    - com.host.plane=cp
  networks:
    - backend_network
  restart: always 
  env_file: "cluster.config"
  ports:
    - "3100"
    - "7946"
  volumes:
    - ./config/loki.yaml:/etc/loki/loki.yaml
    - ./config/overrides.yaml:/etc/overrides.yaml
    - ./rules:/loki/rules:ro

services:

  init:
    image: *loki-img
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/loki"
    volumes:
      - ./loki:/loki
    networks:
      - backend_network

  loki-read:
    <<: *loki
    command: "-config.file=/etc/loki/loki.yaml -runtime-config.file=/etc/overrides.yaml -target=read -config.expand-env=true"
    deploy:
      mode: replicated
      replicas: 3


  loki-write:
    <<: *loki
    command: "-config.file=/etc/loki/loki.yaml -runtime-config.file=/etc/overrides.yaml -target=write -config.expand-env=true"
    deploy:
      mode: replicated
      replicas: 3


