version: "3.7"

networks:
  backend_network:
    name: ${NETWORK_NAME}
    external: true

x-tempo:
  &tempo
  image: grafana/tempo:${VERSION_TEMPO}
  restart: always
  env_file: "cluster.config"
  volumes:
    - ./config/tempo.yaml:/etc/tempo.yaml
  ports:
    - ${TEMPO_SERVER_HTTP_LISTEN_PORT}   # tempo
    - ${TEMPO_SERVER_GRPC_LISTEN_PORT} # tempo grpc
    - "4317"  # otlp grpc
    - "4318"  # otlp http
    - ${TEMPO_MEMBERLIST_BIND_PORT} # memberlist
  networks:
    - backend_network
  labels:
    - ${DOCKER_LABEL_META_TENANT_KEY}=${DOCKER_LABEL_META_TENANT_VALUE}

services:

  tempo-distributor-1:
    <<: *tempo
    command: "-target=distributor -config.file=/etc/tempo.yaml -config.expand-env=true"
    container_name: ${TEMPO_DISTRIBUTOR_1}
    hostname: ${TEMPO_DISTRIBUTOR_1}

  tempo-ingester-1:
    <<: *tempo
    command: "-target=ingester -config.file=/etc/tempo.yaml -config.expand-env=true"
    container_name: ${TEMPO_INGESTER_1}
    hostname: ${TEMPO_INGESTER_1}

  tempo-ingester-2:
    <<: *tempo
    command: "-target=ingester -config.file=/etc/tempo.yaml -config.expand-env=true"
    container_name: ${TEMPO_INGESTER_2}
    hostname: ${TEMPO_INGESTER_2}

  tempo-ingester-3:
    <<: *tempo
    command: "-target=ingester -config.file=/etc/tempo.yaml -config.expand-env=true"
    container_name: ${TEMPO_INGESTER_3}
    hostname: ${TEMPO_INGESTER_3}

  tempo-query-frontend-1:
    <<: *tempo
    command: "-target=query-frontend -config.file=/etc/tempo.yaml -config.expand-env=true"
    container_name: ${TEMPO_QUERY_FRONTEND_1}
    hostname: ${TEMPO_QUERY_FRONTEND_1}

  tempo-querier-1:
    <<: *tempo
    command: "-target=querier -config.file=/etc/tempo.yaml -config.expand-env=true"
    container_name: ${TEMPO_QUERIER_1}
    hostname: ${TEMPO_QUERIER_1}

  tempo-compactor-1:
    <<: *tempo
    command: "-target=compactor -config.file=/etc/tempo.yaml -config.expand-env=true"
    container_name: ${TEMPO_COMPACTOR_1}
    hostname: ${TEMPO_COMPACTOR_1}

  tempo-metrics-generator-1:
    <<: *tempo
    command: "-target=metrics-generator -config.file=/etc/tempo.yaml -config.expand-env=true"
    container_name: ${TEMPO_METRICS_GENERATOR_1}
    hostname: ${TEMPO_METRICS_GENERATOR_1}





















  # otel-test-tempo:
  #   image: grafana/tempo:latest
  #   container_name: otel-test-tempo
  #   hostname: otel-test-tempo
  #   command: ["-config.file=/etc/tempo.yaml" ]
  #   volumes:
  #     - ./config/tempo.yaml:/etc/tempo.yaml
  #   ports:
  #     - "127.0.0.1:14268:14268"  # jaeger ingest
  #     - "127.0.0.1:3200:3200"   # tempo
  #     - "127.0.0.1:9095:9095" # tempo grpc
  #     - "127.0.0.1:4317:4317"  # otlp grpc
  #     - "127.0.0.1:4318:4318"  # otlp http
  #     - "127.0.0.1:9411:9411"   # zipkin
  #   networks:
  #     - otlp_network
  #   labels:
  #     - com.host.plane=cp

  